alias curl=curlie
alias cat=bat
alias cp=xcp
alias cp='cp -iv'
alias mv='mv -iv'
alias la='ls -lahF'
alias gce='gh copilot explain'
alias gbp="git branch -vv | grep ': gone]' | awk '{print \$1}' | xargs git branch -D ; git branches"
alias skip='git update-index --skip-worktree'
alias unskip='git update-index --no-skip-worktree'
alias cd=z
